site_name: Daily Check In
site_url: https://github.com/Sitoi/dailycheckin
repo_url: https://github.com/Sitoi/dailycheckin
site_description: 可基于【腾讯云函数】/【GitHub Actions】/【Docker】的每日签到脚本（支持多账号使用）
repo_name: Sitoi/dailycheckin
site_author: Sitoi
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - 主页: index.md
  - 配置: settings.md
  - 本地使用教程: local.md
  - Docker 使用教程: docker.md
  - 群辉 Docker 使用教程: synology.md
  - 腾讯云函数使用教程: tencent-scf.md
  - GitHub Actions 使用教程: github-actions.md
