site_name: DailyCheckIn
site_url: https://sitoi.gitee.io/dailycheckin/
repo_url: https://gitee.com/sitoi/dailycheckin
site_description: 可基于【腾讯云函数】/【GitHub Actions】/【Docker】的每日签到脚本（支持多账号使用）
repo_name: Sitoi/dailycheckin
site_author: Sitoi
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - 主页: index.md
  - 安装:
      - 本地: local.md
      - 青龙: qinglong.md
      - 群辉: synology.md
      - 云函数: tencent-scf.md
      - Docker: docker.md
      - elecV2P: elecV2P.md
  - 配置: settings.md