name: 部署到腾讯云函数

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "安装依赖和 serverless 工具"
        run: |
          npm install
          sudo npm install serverless -g

      - name: "将 Secrets 里面配置的变量渲染成 config.json 文件"
        run: |
          python3.7 config.py
        env: #因为直接读取secrets里面的值很多字符不会自动转译，导致写入serverless.yml异常，所以设置到环境变量，在读取环境变量转译过的值
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          DINGTALK_ACCESS_TOKEN: ${{secrets.DINGTALK_ACCESS_TOKEN}}
          SCKEY: ${{secrets.SCKEY}}
          SENDKEY: ${{secrets.SENDKEY}}
          BARK_URL: ${{secrets.BARK_URL}}
          QMSG_KEY: ${{secrets.QMSG_KEY}}
          QMSG_TYPE: ${{secrets.QMSG_TYPE}}
          TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{secrets.TG_USER_ID}}
          COOLPUSHSKEY: ${{secrets.COOLPUSHSKEY}}
          COOLPUSHQQ: ${{secrets.COOLPUSHQQ}}
          COOLPUSHWX: ${{secrets.COOLPUSHWX}}
          COOLPUSHEMAIL: ${{secrets.COOLPUSHEMAIL}}
          QYWX_KEY: ${{secrets.QYWX_KEY}}
          QYWX_CORPID: ${{secrets.QYWX_CORPID}}
          QYWX_AGENTID: ${{secrets.QYWX_AGENTID}}
          QYWX_CORPSECRET: ${{secrets.QYWX_CORPSECRET}}
          QYWX_TOUSER: ${{secrets.QYWX_TOUSER}}
          PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
          PUSHPLUS_TOPIC: ${{secrets.PUSHPLUS_TOPIC}}
          CITY_NAME_LIST: ${{secrets.CITY_NAME_LIST}}
          MOTTO: ${{secrets.MOTTO}}
          IQIYI_COOKIE_LIST: ${{secrets.IQIYI_COOKIE_LIST}}
          VQQ_COOKIE_LIST: ${{secrets.VQQ_COOKIE_LIST}}
          YOUDAO_COOKIE_LIST: ${{secrets.YOUDAO_COOKIE_LIST}}
          KGQQ_COOKIE_LIST: ${{secrets.KGQQ_COOKIE_LIST}}
          MUSIC163_ACCOUNT_LIST: ${{secrets.MUSIC163_ACCOUNT_LIST}}
          XMLY_COOKIE_LIST: ${{secrets.XMLY_COOKIE_LIST}}
          ONEPLUSBBS_COOKIE_LIST: ${{secrets.ONEPLUSBBS_COOKIE_LIST}}
          FMAPP_ACCOUNT_LIST: ${{secrets.FMAPP_ACCOUNT_LIST}}
          BAIDU_URL_SUBMIT_LIST: ${{secrets.BAIDU_URL_SUBMIT_LIST}}
          TIEBA_COOKIE_LIST: ${{secrets.TIEBA_COOKIE_LIST}}
          BILIBILI_COOKIE_LIST: ${{secrets.BILIBILI_COOKIE_LIST}}
          LIANTONG_ACCOUNT_LIST: ${{secrets.LIANTONG_ACCOUNT_LIST}}
          V2EX_COOKIE_LIST: ${{secrets.V2EX_COOKIE_LIST}}
          WWW2NZZ_COOKIE_LIST: ${{secrets.WWW2NZZ_COOKIE_LIST}}
          SMZDM_COOKIE_LIST: ${{secrets.SMZDM_COOKIE_LIST}}
          MIMOTION_ACCOUNT_LIST: ${{secrets.MIMOTION_ACCOUNT_LIST}}
          ACFUN_ACCOUNT_LIST: ${{secrets.ACFUN_ACCOUNT_LIST}}
          CLOUD189_ACCOUNT_LIST: ${{secrets.CLOUD189_ACCOUNT_LIST}}
          WPS_COOKIE_LIST: ${{secrets.WPS_COOKIE_LIST}}
          POJIE_COOKIE_LIST: ${{secrets.POJIE_COOKIE_LIST}}
          MGTV_PARAMS_LIST: ${{secrets.MGTV_PARAMS_LIST}}
          PICACOMIC_ACCOUNT_LIST: ${{secrets.PICACOMIC_ACCOUNT_LIST}}
          MEIZU_COOKIE_LIST: ${{secrets.MEIZU_COOKIE_LIST}}
          CAIYUN_COOKIE_LIST: ${{secrets.CAIYUN_COOKIE_LIST}}
          ZHIYOO_COOKIE_LIST: ${{secrets.ZHIYOO_COOKIE_LIST}}

      - name: "部署到腾讯云函数"
        run: sls deploy --debug
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
