name: 每日签到合集

on:
  schedule:
    - cron: '45 0 * * * '
  watch:
    types: [ started ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: '运行【每日签到合集】'
        run: python3 index.py
        env:
          IS_GITHUB_ACTION: true
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          DINGTALK_ACCESS_TOKEN: ${{secrets.DINGTALK_ACCESS_TOKEN}}
          SCKEY: ${{secrets.SCKEY}}
          SENDKEY: ${{secrets.SENDKEY}}
          BARK_URL: ${{secrets.BARK_URL}}
          QMSG_KEY: ${{secrets.QMSG_KEY}}
          QMSG_TYPE: ${{secrets.QMSG_TYPE}}
          TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{secrets.TG_USER_ID}}
          COOLPUSHSKEY: ${{secrets.COOLPUSHSKEY}}
          COOLPUSHQQ: ${{secrets.COOLPUSHQQ}}
          COOLPUSHWX: ${{secrets.COOLPUSHWX}}
          COOLPUSHEMAIL: ${{secrets.COOLPUSHEMAIL}}
          QYWX_KEY: ${{secrets.QYWX_KEY}}
          QYWX_CORPID: ${{secrets.QYWX_CORPID}}
          QYWX_AGENTID: ${{secrets.QYWX_AGENTID}}
          QYWX_CORPSECRET: ${{secrets.QYWX_CORPSECRET}}
          QYWX_TOUSER: ${{secrets.QYWX_TOUSER}}
          PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
          PUSHPLUS_TOPIC: ${{secrets.PUSHPLUS_TOPIC}}
          CITY_NAME_LIST: ${{secrets.CITY_NAME_LIST}}
          MOTTO: ${{secrets.MOTTO}}
          IQIYI_COOKIE_LIST: ${{secrets.IQIYI_COOKIE_LIST}}
          VQQ_COOKIE_LIST: ${{secrets.VQQ_COOKIE_LIST}}
          YOUDAO_COOKIE_LIST: ${{secrets.YOUDAO_COOKIE_LIST}}
          KGQQ_COOKIE_LIST: ${{secrets.KGQQ_COOKIE_LIST}}
          MUSIC163_ACCOUNT_LIST: ${{secrets.MUSIC163_ACCOUNT_LIST}}
          ONEPLUSBBS_COOKIE_LIST: ${{secrets.ONEPLUSBBS_COOKIE_LIST}}
          FMAPP_ACCOUNT_LIST: ${{secrets.FMAPP_ACCOUNT_LIST}}
          BAIDU_URL_SUBMIT_LIST: ${{secrets.BAIDU_URL_SUBMIT_LIST}}
          TIEBA_COOKIE_LIST: ${{secrets.TIEBA_COOKIE_LIST}}
          BILIBILI_COOKIE_LIST: ${{secrets.BILIBILI_COOKIE_LIST}}
          LIANTONG_ACCOUNT_LIST: ${{secrets.LIANTONG_ACCOUNT_LIST}}
          V2EX_COOKIE_LIST: ${{secrets.V2EX_COOKIE_LIST}}
          WWW2NZZ_COOKIE_LIST: ${{secrets.WWW2NZZ_COOKIE_LIST}}
          SMZDM_COOKIE_LIST: ${{secrets.SMZDM_COOKIE_LIST}}
          MIMOTION_ACCOUNT_LIST: ${{secrets.MIMOTION_ACCOUNT_LIST}}
          ACFUN_ACCOUNT_LIST: ${{secrets.ACFUN_ACCOUNT_LIST}}
          CLOUD189_ACCOUNT_LIST: ${{secrets.CLOUD189_ACCOUNT_LIST}}
          WPS_COOKIE_LIST: ${{secrets.WPS_COOKIE_LIST}}
          POJIE_COOKIE_LIST: ${{secrets.POJIE_COOKIE_LIST}}
          MGTV_PARAMS_LIST: ${{secrets.MGTV_PARAMS_LIST}}
          PICACOMIC_ACCOUNT_LIST: ${{secrets.PICACOMIC_ACCOUNT_LIST}}
          MEIZU_COOKIE_LIST: ${{secrets.MEIZU_COOKIE_LIST}}
          ZHIYOO_COOKIE_LIST: ${{secrets.ZHIYOO_COOKIE_LIST}}
          WEIBO_COOKIE_LIST: ${{secrets.WEIBO_COOKIE_LIST}}
          DUOKAN_COOKIE_LIST: ${{secrets.DUOKAN_COOKIE_LIST}}
          CSDN_COOKIE_LIST: ${{secrets.CSDN_COOKIE_LIST}}
          WZYD_DATA_LIST: ${{secrets.WZYD_DATA_LIST}}
